name: My First Workflow

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6
        
        - name: Welcome message and List and Read file
          run: |
            echo "My first Github Actions Job"
            echo
            echo "veamos nuestro current path"
            pwd
            echo
            echo "ahora vamos a listar"
            ls -la
            echo
            echo "ahora vamos a revisar el tree"
            tree -a
            echo
            echo "ahora vamos a ver lo que hay en el README.md"
            cat README.md
            echo
            echo "ahora vamos a movernos al home"
            cd
            echo
            echo "veamos nuestro current path"
            pwd
            echo
            echo "ahora vamos a listar"
            ls -la
            echo
            echo "ahora vamos a revisar el tree"
            tree -a
        
        #- name: Generate ASCII Artwork
        #  run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        
          #- name: Welcome message
        #  run: echo "My first Github Actions Job"
        
        #- name: List files
        #  run: ls
        
        #- name: Read file
        #  run: cat README.md