name: Workflow Filters and Activities

on:
    workflow_dispatch:
#    schedule:
#        - cron: "*/59 * * * *"
    push:
#        branches-ignore:
#            - feature/*
#            - test/**
        branches:
            - main
            - '!feature/*'      # ignore (by using !) all the branch name starting with 'feature'
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:           # when a pull request that includes a change on any file other than README.md
            - README.md
        branches:               # configures your workflow to only run on pull requests that target specific branches
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for event type -  ${{ github.event_name }}

# link (Skipping workflow runs): https://docs.github.com/en/actions/how-tos/manage-workflow-runs/skip-workflow-runs?versionId=free-pro-team%40latest&productId=actions&restPage=reference%2Cworkflows-and-actions%2Ccontexts